/* добавя текст към снимките, когато бъдат кликнати */

document.getElementById("div1").onclick = function() {myFunction1()};
function myFunction1() {
  document.getElementById("div1").innerHTML = "In the center of nearby star-forming region lies a huge cluster containing some of the largest, hottest, and most massive stars known. These stars, known collectively as star cluster R136, part of the Tarantula Nebula, were captured in the featured image in visible light in 2009 through the Hubble Space Telescope. Gas and dust clouds in the Tarantula Nebula, have been sculpted into elongated shapes by powerful winds and ultraviolet radiation from these hot cluster stars. The Tarantula Nebula lies within a neighboring galaxy known as the Large Magellanic Cloud and is located a mere 170,000 light-years away.";
}

document.getElementById("div2").onclick = function() {myFunction2()};
function myFunction2() {
  document.getElementById("div2").innerHTML = "The jets emanating from Centaurus A are over a million light years long. These jets of streaming plasma, expelled by a giant black hole in the center of this spiral galaxy, light up this composite image of Cen A. Exactly how the central black hole expels infalling matter remains unknown. After clearing the galaxy, however, the jets inflate large radio bubbles that likely glow for millions of years. If energized by a passing gas cloud, the radio bubbles can even light up again after billions of years. X-ray light is depicted in the featured composite image in blue, while microwave light is colored orange. The base of the jet in radio light shows details of the innermost light year of the central jet.";
}

document.getElementById("div3").onclick = function() {myFunction3()};
function myFunction3() {
  document.getElementById("div3").innerHTML = "Clouds of glowing hydrogen gas fill this colorful skyscape in the faint but fanciful constellation Monoceros, the Unicorn. A star forming region cataloged as NGC 2264, the complex jumble of cosmic gas and dust is about 2,700 light-years distant and mixes reddish emission nebulae excited by energetic light from newborn stars with dark interstellar dust clouds. Where the otherwise obscuring dust clouds lie close to the hot, young stars they also reflect starlight, forming blue reflection nebulae. The telescopic image spans about 1.5 degrees or 3 full moons, covering nearly 80 light-years at the distance of NGC 2264. Its cast of cosmic characters includes the the Fox Fur Nebula, whose dusty, convoluted pelt lies left of center, bright variable star S Monocerotis immersed in the blue-tinted haze near center, and the Cone Nebula pointing in from the right side of the frame. Of course, the stars of NGC 2264 are also known as the Christmas Tree star cluster. The triangular tree shape is seen on its side here. Traced by brighter stars it has its apex at the Cone Nebula. The tree's broader base is centered near S Monocerotis.";
}

document.getElementById("div4").onclick = function() {myFunction4()};
function myFunction4() {
  document.getElementById("div4").innerHTML = "The Tarantula Nebula, also known as 30 Doradus, is more than a thousand light-years in diameter, a giant star forming region within nearby satellite galaxy the Large Magellanic Cloud. About 180 thousand light-years away, it's the largest, most violent star forming region known in the whole Local Group of galaxies. The cosmic arachnid sprawls across the top of this spectacular view, composed with narrowband filter data centered on emission from ionized hydrogen and oxygen atoms. Within the Tarantula (NGC 2070), intense radiation, stellar winds and supernova shocks from the central young cluster of massive stars, cataloged as R136, energize the nebular glow and shape the spidery filaments. Around the Tarantula are other star forming regions with young star clusters, filaments, and blown-out bubble-shaped clouds. In fact, the frame includes the site of the closest supernova in modern times, SN 1987A, right of center. The rich field of view spans about 2 degrees or 4 full moons, in the southern constellation Dorado. But were the Tarantula Nebula closer, say 1,500 light-years distant like the local star forming Orion Nebula, it would take up half the sky.";
}

document.getElementById("div5").onclick = function() {myFunction5()};
function myFunction5() {
  document.getElementById("div5").innerHTML = "What powers this unusual nebula? CTB-1 is the expanding gas shell that was left when a massive star toward the constellation of Cassiopeia exploded about 10,000 years ago. The star likely detonated when it ran out of elements, near its core, that could create stabilizing pressure with nuclear fusion. The resulting supernova remnant, nicknamed the Medulla Nebula for its brain-like shape, still glows in visible light by the heat generated by its collision with confining interstellar gas. Why the nebula also glows in X-ray light, though, remains a mystery. One hypothesis holds that an energetic pulsar was co-created that powers the nebula with a fast outwardly moving wind. Following this lead, a pulsar has recently been found in radio waves that appears to have been expelled by the supernova explosion at over 1000 kilometers per second. Although the Medulla Nebula appears as large as a full moon, it is so faint that it took 130-hours of exposure with two small telescopes in New Mexico, USA, to create the featured image.";
}

document.getElementById("div6").onclick = function() {myFunction6()};
function myFunction6() {
  document.getElementById("div6").innerHTML = "Barred spiral galaxy NGC 1365 is truly a majestic island universe some 200,000 light-years across. Located a mere 60 million light-years away toward the chemical constellation Fornax, NGC 1365 is a dominant member of the well-studied Fornax Cluster of galaxies. This impressively sharp color image shows the intense, reddish star forming regions near the ends of central bar and along the spiral arms, with details of the obscuring dust lanes cutting across the galaxy's bright core. At the core lies a supermassive black hole. Astronomers think NGC 1365's prominent bar plays a crucial role in the galaxy's evolution, drawing gas and dust into a star-forming maelstrom and ultimately feeding material into the central black hole.";
}

/* изтрива текста, когато курсурът зилезе извъм див със снимка*/

function noText() {
        document.getElementById("div1").innerHTML = "";
		document.getElementById("div2").innerHTML = "";
		document.getElementById("div3").innerHTML = "";
		document.getElementById("div4").innerHTML = "";
		document.getElementById("div5").innerHTML = "";
		document.getElementById("div6").innerHTML = "";
}

/* смятането на секундите */

document.getElementById("btn").onclick = function() {myFunction()};

function myFunction(){
var DateDiff = {
 
    inDays: function(d1, d2) {
        var t2 = d2.getTime();
        var t1 = d1.getTime();
 
        return parseInt((t2-t1)/(24*3600*1000));
    },
 
    inWeeks: function(d1, d2) {
        var t2 = d2.getTime();
        var t1 = d1.getTime();
 
        return parseInt((t2-t1)/(24*3600*1000*7));
    },
 
    inMonths: function(d1, d2) {
        var d1Y = d1.getFullYear();
        var d2Y = d2.getFullYear();
        var d1M = d1.getMonth();
        var d2M = d2.getMonth();
 
        return (d2M+12*d2Y)-(d1M+12*d1Y);
    },
 
    inYears: function(d1, d2) {
        return d2.getFullYear()-d1.getFullYear();
    }
}
 
var dString = document.getElementById("dt1").value;  /* защото е календар*/
 
var d1 = new Date(dString);
var d2 = new Date();

/* вкарва изхода от функцията в листа */

document.getElementById("li1").innerHTML = ("<br />Number of <b>years</b> since "+dString+": "+DateDiff.inYears(d1, d2));
document.getElementById("li2").innerHTML = ("<br />Number of <b>months</b> since "+dString+": "+DateDiff.inMonths(d1, d2));
document.getElementById("li3").innerHTML = ("<br />Number of <b>weeks</b> since "+dString+": "+DateDiff.inWeeks(d1, d2));
document.getElementById("li4").innerHTML = ("<br />Number of <b>days</b> since "+dString+": "+DateDiff.inDays(d1, d2));
document.getElementById("li5").innerHTML = ("<br />Number of <b>hours</b> since "+dString+": "+DateDiff.inDays(d1, d2)*24);
document.getElementById("li6").innerHTML = ("<br />Number of <b>minutes</b> since "+dString+": "+DateDiff.inDays(d1, d2)*24*60);
document.getElementById("li7").innerHTML = ("<br />Number of <b>seconds</b> since "+dString+": "+DateDiff.inDays(d1, d2)*24*60*60);
}